#!/usr/bin/env ruby
# Ruby on Rails console.

# Turn ActiveRecord's logging off and on.

def log_off
  puts "== Logging to log file."
  ActiveRecord::Base.logger.level = 1  # warn (?)
  nil
end

def log_on
  puts "== Logging to console."
  ActiveRecord::Base.logger.level = 0  # debug (?)
  nil
end
 
